/**
 * Table extraction profiles (metadata only — no book text).
 * startHeading / endHeading match PDF appendix section titles.
 */

/** @type {Array<Record<string, unknown>>} */
export const profiles = [
  {
    slug: "clear-blocker-table",
    title: "Clear Blocker Table",
    printedPage: 158,
    startHeading: "CLEAR BLOCKER TABLE",
    endHeading: "LOCATION GENERATION TABLES",
    layout: "singleColumn",
    rollMin: 1,
    rollMax: 100,
  },
  {
    slug: "inhabitants-generator",
    title: "Inhabitants Generator",
    printedPage: 159,
    startHeading: "Inhabitants Generator",
    endHeading: "Location Icon Generator",
    layout: "bandedRows",
    rollMin: 1,
    rollMax: 20,
  },
  {
    slug: "location-icon-generator",
    title: "Location Icon Generator",
    printedPage: 159,
    startHeading: "Location Icon Generator",
    endHeading: "Wasteland Truth Generator",
    layout: "nameEqualsDescription",
    rollMin: 1,
    rollMax: 20,
    nameEqualsDescription: true,
  },
  {
    slug: "wasteland-truth-generator",
    title: "Wasteland Truth Generator",
    printedPage: 160,
    startHeading: "Wasteland Truth Generator",
    endHeading: "Settlement Truth Generator",
    layout: "twoColumnTruth",
    rollMin: 1,
    rollMax: 20,
  },
  {
    slug: "settlement-truth-generator",
    title: "Settlement Truth Generator",
    printedPage: 161,
    startHeading: "Settlement Truth Generator",
    endHeading: "ENCOUNTER GENERATION TABLES",
    layout: "twoColumnTruth",
    rollMin: 1,
    rollMax: 20,
  },
  {
    slug: "settlement-encounter",
    title: "Settlement Encounter",
    printedPage: 162,
    startHeading: "Settlement Encounter",
    endHeading: "Wasteland Encounter",
    layout: "twoColumnD20",
    rollMin: 1,
    rollMax: 20,
  },
  {
    slug: "wasteland-encounter",
    title: "Wasteland Encounter",
    printedPage: 164,
    startHeading: "Wasteland Encounter",
    endHeading: "Combat States",
    layout: "twoColumnD20",
    rollMin: 1,
    rollMax: 20,
  },
  {
    slug: "combat-states",
    title: "Combat States",
    printedPage: 166,
    startHeading: "Combat States",
    endHeading: "Quantity",
    layout: "twoColumnState",
    rollMin: 1,
    rollMax: 20,
  },
  {
    slug: "quantity-table",
    title: "Quantity",
    printedPage: 167,
    startHeading: "Quantity",
    endHeading: "EQUIPMENT TABLES",
    layout: "nameEqualsDescription",
    rollMin: 1,
    rollMax: 20,
    nameEqualsDescription: true,
  },
  {
    slug: "conditions-table",
    title: "Conditions",
    printedPage: 168,
    startHeading: "Conditions",
    endHeading: "Modifications",
    layout: "nameEqualsDescription",
    rollMin: 1,
    rollMax: 20,
    nameEqualsDescription: true,
  },
  {
    slug: "equipment-armor-mods",
    title: "Armor Modifications",
    printedPage: 168,
    startHeading: "Modifications",
    endHeading: "Loot Generation Table",
    layout: "twoColumnMods",
    modColumn: "armor",
    rollMin: 1,
    rollMax: 20,
  },
  {
    slug: "equipment-weapon-mods",
    title: "Weapon Modifications",
    printedPage: 168,
    startHeading: "Modifications",
    endHeading: "Loot Generation Table",
    layout: "twoColumnMods",
    modColumn: "weapon",
    rollMin: 1,
    rollMax: 20,
  },
  {
    slug: "loot-generation-table",
    title: "Loot Generation Table",
    printedPage: 170,
    startHeading: "Loot Generation Table",
    endHeading: "Armor",
    layout: "bandedRows",
    rollMin: 1,
    rollMax: 20,
  },
  {
    slug: "loot-armor",
    title: "Armor",
    printedPage: 171,
    startHeading: "Armor",
    endHeading: "Caps",
    layout: "bandedRows",
    rollMin: 1,
    rollMax: 20,
  },
  {
    slug: "loot-caps",
    title: "Caps",
    printedPage: 171,
    startHeading: "Caps",
    endHeading: "Supplies",
    layout: "bandedRows",
    rollMin: 1,
    rollMax: 20,
  },
  {
    slug: "loot-supplies",
    title: "Supplies",
    printedPage: 172,
    startHeading: "Supplies",
    endHeading: "Chems",
    layout: "nameEqualsDescription",
    rollMin: 1,
    rollMax: 20,
    nameEqualsDescription: true,
    description:
      "Whenever you gain an item from this list, you gain a Stack of Supplies.",
  },
  {
    slug: "loot-chems",
    title: "Chems",
    printedPage: 172,
    startHeading: "Chems",
    endHeading: "Ranged Weapons",
    layout: "bandedRows",
    rollMin: 2,
    rollMax: 20,
    description:
      "Roll a d20 to determine the Result; on a roll of 1 re-roll twice on the table.",
  },
  {
    slug: "loot-ranged-weapons",
    title: "Ranged Weapons",
    printedPage: 174,
    startHeading: "Ranged Weapons",
    endHeading: "Melee Weapons",
    layout: "threeColumnSum",
    rollMin: 2,
    rollMax: 40,
    formula: "2d40",
  },
  {
    slug: "loot-melee-weapons",
    title: "Melee Weapons",
    printedPage: 175,
    startHeading: "Melee Weapons",
    endHeading: "Thrown Weapons and Explosives",
    layout: "threeColumnSum",
    rollMin: 2,
    rollMax: 40,
    formula: "2d40",
  },
  {
    slug: "loot-thrown-explosives",
    title: "Thrown Weapons and Explosives",
    printedPage: 175,
    startHeading: "Thrown Weapons and Explosives",
    endHeading: "Oddities",
    layout: "bandedRows",
    rollMin: 1,
    rollMax: 20,
  },
  {
    slug: "loot-oddities",
    title: "Oddities",
    printedPage: 176,
    startHeading: "Oddities",
    endHeading: "Scrap",
    layout: "bandedRows",
    rollMin: 1,
    rollMax: 20,
  },
  {
    slug: "loot-scrap",
    title: "Scrap",
    printedPage: 177,
    startHeading: "Scrap",
    endHeading: "GENERATE NPC",
    layout: "threeColumnSum",
    rollMin: 2,
    rollMax: 40,
    formula: "2d40",
  },
  {
    slug: "npc-age",
    title: "NPC Age",
    printedPage: 180,
    startHeading: "NPC Age",
    endHeading: "NPC Demeanor",
    layout: "bandedRows",
    rollMin: 1,
    rollMax: 20,
  },
  {
    slug: "npc-demeanor-odds",
    title: "NPC Demeanor (Odds)",
    printedPage: 181,
    startHeading: "NPC Demeanor",
    endHeading: "NPC Distinctive Features",
    layout: "demeanorColumn",
    demeanorColumn: "odds",
    rollMin: 1,
    rollMax: 20,
    nameEqualsDescription: true,
    description: "Roll d20; on Odd result use this table, on Even use NPC Demeanor (Evens).",
  },
  {
    slug: "npc-demeanor-evens",
    title: "NPC Demeanor (Evens)",
    printedPage: 181,
    startHeading: "NPC Demeanor",
    endHeading: "NPC Distinctive Features",
    layout: "demeanorColumn",
    demeanorColumn: "evens",
    rollMin: 1,
    rollMax: 20,
    nameEqualsDescription: true,
  },
  {
    slug: "npc-distinctive-features",
    title: "NPC Distinctive Features",
    printedPage: 182,
    startHeading: "NPC Distinctive Features",
    endHeading: "NPC Profession",
    layout: "nameEqualsDescription",
    rollMin: 1,
    rollMax: 20,
    nameEqualsDescription: true,
    xBands: { resultL: [45, 70], labelL: [75, 200], resultR: [999, 999], labelR: [999, 999] },
    description: "Roll twice on this table. Profile encodes ROLL ONE column only.",
  },
  {
    slug: "npc-profession",
    title: "NPC Profession",
    printedPage: 182,
    startHeading: "NPC Profession",
    endHeading: "NPC Secret Table",
    layout: "nameEqualsDescription",
    rollMin: 1,
    rollMax: 20,
    nameEqualsDescription: true,
  },
  {
    slug: "npc-secret",
    title: "NPC Secret Table",
    printedPage: 183,
    startHeading: "NPC Secret Table",
    endHeading: "NPC Truth",
    layout: "npcSecret",
    rollMin: 1,
    rollMax: 20,
  },
  {
    slug: "npc-truth",
    title: "NPC Truth",
    printedPage: 184,
    startHeading: "NPC Truth",
    endHeading: "DANGEROUS NPC",
    layout: "npcTruth",
    rollMin: 1,
    rollMax: 20,
  },
  {
    slug: "dangerous-npc-threat",
    title: "Dangerous NPC Threat",
    printedPage: 185,
    startHeading: "Dangerous NPC Threat",
    endHeading: "Dangerous NPC Special Ability",
    layout: "bandedRows",
    rollMin: 1,
    rollMax: 20,
  },
  {
    slug: "dangerous-npc-special-ability",
    title: "Dangerous NPC Special Ability",
    printedPage: 186,
    startHeading: "Dangerous NPC Special Ability",
    endHeading: "Dangerous NPC Weapons",
    layout: "bandedRows",
    rollMin: 1,
    rollMax: 20,
  },
  {
    slug: "dangerous-npc-weapons",
    title: "Dangerous NPC Weapons",
    printedPage: 188,
    startHeading: "Dangerous NPC Weapons",
    endHeading: "Dangerous NPC Group",
    layout: "bandedRows",
    rollMin: 1,
    rollMax: 20,
  },
  {
    slug: "dangerous-npc-group",
    title: "Dangerous NPC Group",
    printedPage: 188,
    startHeading: "Dangerous NPC Group",
    endHeading: "GENERATE FOE",
    layout: "bandedRows",
    rollMin: 1,
    rollMax: 20,
  },
  {
    slug: "foe-type",
    title: "Foe Type",
    printedPage: 189,
    startHeading: "Foe Type",
    endHeading: "Creature Foe Generation Table",
    layout: "bandedRows",
    rollMin: 1,
    rollMax: 20,
  },
  {
    slug: "foe-creature-generator",
    title: "Creature Foe Generation Table",
    printedPage: 189,
    startHeading: "Creature Foe Generation Table",
    endHeading: "Super Mutants Foe Generation Table",
    layout: "foeGenerator",
    rollMin: 1,
    rollMax: 20,
  },
  {
    slug: "foe-super-mutant-generator",
    title: "Super Mutants Foe Generation Table",
    printedPage: 190,
    startHeading: "Super Mutants Foe Generation Table",
    endHeading: "Feral Ghouls Foe Generation Table",
    layout: "foeGenerator",
    rollMin: 1,
    rollMax: 20,
  },
  {
    slug: "foe-feral-ghoul-generator",
    title: "Feral Ghouls Foe Generation Table",
    printedPage: 191,
    startHeading: "Feral Ghouls Foe Generation Table",
    endHeading: "Robots Foe Generation Table",
    layout: "foeGenerator",
    rollMin: 1,
    rollMax: 20,
  },
  {
    slug: "foe-robot-generator",
    title: "Robots Foe Generation Table",
    printedPage: 191,
    startHeading: "Robots Foe Generation Table",
    endHeading: "Raiders Foe Generation Table",
    layout: "foeGenerator",
    rollMin: 1,
    rollMax: 20,
  },
  {
    slug: "foe-raider-generator",
    title: "Raiders Foe Generation Table",
    printedPage: 192,
    startHeading: "Raiders Foe Generation Table",
    endHeading: "The Institute Foe Generation Table",
    layout: "foeGenerator",
    rollMin: 1,
    rollMax: 20,
  },
  {
    slug: "foe-institute-generator",
    title: "The Institute Foe Generation Table",
    printedPage: 192,
    startHeading: "The Institute Foe Generation Table",
    endHeading: "Brotherhood of Steel Foe Generation Table",
    layout: "foeGenerator",
    rollMin: 1,
    rollMax: 20,
  },
  {
    slug: "foe-brotherhood-of-steel-generator",
    title: "Brotherhood of Steel Foe Generation Table",
    printedPage: 193,
    startHeading: "Brotherhood of Steel Foe Generation Table",
    endHeading: "Zetans Foe Generation Table",
    layout: "foeGenerator",
    rollMin: 1,
    rollMax: 20,
  },
  {
    slug: "foe-zetan-generator",
    title: "Zetans Foe Generation Table",
    printedPage: 194,
    startHeading: "Zetans Foe Generation Table",
    endHeading: "GENERATE SIDE QUEST",
    layout: "foeGenerator",
    rollMin: 1,
    rollMax: 20,
  },
  {
    slug: "side-quest-generate-reward",
    title: "Generate Reward",
    printedPage: 194,
    startHeading: "Generate Reward",
    endHeading: "Generate Goal Type",
    layout: "singleColumn",
    rollMin: 1,
    rollMax: 100,
  },
  {
    slug: "side-quest-goal-type",
    title: "Generate Goal Type",
    printedPage: 196,
    startHeading: "Generate Goal Type",
    endHeading: "Goals",
    layout: "nameEqualsDescription",
    rollMin: 1,
    rollMax: 20,
    nameEqualsDescription: true,
  },
  ...goalProfiles(),
  {
    slug: "random-faction",
    title: "Random Faction",
    printedPage: 217,
    startHeading: "Random Faction",
    endHeading: "Injury",
    layout: "nameEqualsDescription",
    rollMin: 1,
    rollMax: 20,
    nameEqualsDescription: true,
  },
  {
    slug: "injury-table",
    title: "Injury Table",
    printedPage: 217,
    printedPageEnd: 217,
    startHeading: "Injury",
    endHeading: "Miraculous Escape",
    layout: "bandedRows",
    rollMin: 1,
    rollMax: 20,
  },
  {
    slug: "miraculous-escape",
    title: "Miraculous Escape",
    printedPage: 218,
    printedPageEnd: 218,
    startHeading: "Miraculous Escape",
    exactStart: true,
    endHeading: "Reputation",
    xBands: { range: [38, 75], primary: [76, 140], secondary: [141, 520] },
    layout: "bandedRows",
    rollMin: 1,
    rollMax: 20,
  },
  {
    slug: "reputation-table",
    title: "Reputation Table",
    printedPage: 218,
    printedPageEnd: 218,
    startHeading: "Reputation",
    exactStart: true,
    endHeading: "FOE STAT BLOCKS",
    layout: "bandedRows",
    rollMin: 1,
    rollMax: 20,
    xBands: { range: [38, 55], primary: [56, 140], secondary: [141, 520] },
  },
];

function goalProfiles() {
  const goals = [
    ["vengeance", "Vengeance"],
    ["money", "Money"],
    ["family", "Family"],
    ["community", "Community"],
    ["information", "Information"],
    ["fame", "Fame"],
    ["power", "Power"],
    ["love", "Love"],
    ["survival", "Survival"],
    ["food", "Food"],
    ["obsession", "Obsession"],
    ["excitement", "Excitement"],
    ["purpose", "Purpose"],
    ["redemption", "Redemption"],
    ["distraction", "Distraction"],
    ["safety", "Safety"],
    ["escape", "Escape"],
    ["technology", "Technology"],
  ];
  return goals.map(([slug, title], i) => {
    const next = goals[i + 1];
    const printedPage = i === 16 ? 215 : i === 17 ? 216 : 197 + i;
    return {
      slug: `side-quest-goal-${slug}`,
      title,
      printedPage,
      printedPageEnd: printedPage + 1,
      startHeading: title,
      endHeading: next ? next[1] : "Random Faction",
      layout: "goalSubTable",
      rollMin: 1,
      rollMax: 20,
    };
  });
}

/**
 * @param {string} [slug]
 */
export function getProfile(slug) {
  if (!slug) return profiles;
  const key = slug.toLowerCase().replace(/\.json$/i, "");
  return profiles.find((p) => p.slug === key);
}
