/** GM Toolkit random encounter table extraction profiles (PDF pages 20–24). */
export const profiles = [
  {
    slug: "random-encounter-type",
    title: "Random Encounter Type",
    layout: "gmToolkitEncounterType",
    pdfPage: 20,
    pdfPageEnd: 20,
    yMin: 490,
    yMax: 590,
    rollMin: 1,
    rollMax: 20,
    formula: "1d20",
    nameEqualsDescription: true,
  },
  {
    slug: "random-ordinary-encounters",
    title: "Random Ordinary Encounters",
    layout: "gmToolkitTitleBody",
    pdfPage: 21,
    pdfPageEnd: 21,
    yMin: 60,
    yMax: 710,
    rollMin: 1,
    rollMax: 20,
    formula: "1d20",
  },
  {
    slug: "random-object-encounters",
    title: "Random Object Encounters",
    layout: "gmToolkitTitleBody",
    pdfPage: 22,
    pdfPageEnd: 22,
    yMin: 60,
    yMax: 710,
    contentMinX: 108,
    rollMin: 1,
    rollMax: 20,
    formula: "1d20",
  },
  {
    slug: "random-campsite-encounters",
    title: "Random Campsite Encounters",
    layout: "gmToolkitTitleBody",
    pdfPage: 23,
    pdfPageEnd: 23,
    yMin: 430,
    yMax: 710,
    rollMin: 1,
    rollMax: 20,
    formula: "1d20",
  },
  {
    slug: "random-choke-point-encounters",
    title: "Random Choke Point Encounters",
    layout: "gmToolkitTitleBody",
    pdfPage: 23,
    pdfPageEnd: 23,
    yMin: 60,
    yMax: 400,
    rollMin: 1,
    rollMax: 20,
    formula: "1d20",
  },
  {
    slug: "random-factions-animosity",
    title: "Random Factions for Animosity Encounters",
    layout: "gmToolkitTitleBody",
    pdfPage: 24,
    pdfPageEnd: 24,
    yMin: 130,
    yMax: 450,
    contentMinX: 108,
    rollMin: 1,
    rollMax: 20,
    formula: "2d20",
  },
];
